title: "My UMLS API Client Project"
description: "A UMLS API Client for interacting with healthcare data"
theme: jekyll-theme-cayman  # Specify the theme here
author: Palash Thakur
email: palasht75@gmail.com
repository: https://github.com/palasht75/umls-client
