title: "UMLS API Client"
description: "Interact with UMLS data"
theme: jekyll-theme-cayman
author: Palash Thakur
email: palasht75@gmail.com
repository: https://github.com/palasht75/umls-python-client
github:
  repository_url: https://github.com/palasht75/umls-python-client
  

# Navigation Links
header_pages:
  - index.md
  - docs.md
  - about.md
  - contributors.md
  - sourceAPI
  - crosswalkAPI
  - searchAPI
  - semanticAPI
